# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(1319, 890)
        self.centralwidget = QtWidgets.QWidget(dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_btn.setGeometry(QtCore.QRect(910, 20, 161, 51))
        self.upload_btn.setObjectName("upload_btn")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(50, 10, 801, 871))
        self.graphicsView.setObjectName("graphicsView")
        self.rotate_left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_left_btn.setGeometry(QtCore.QRect(890, 100, 91, 41))
        self.rotate_left_btn.setObjectName("rotate_left_btn")
        self.rotate_right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_right_btn.setGeometry(QtCore.QRect(1010, 100, 91, 41))
        self.rotate_right_btn.setObjectName("rotate_right_btn")
        self.zoom_in_btn = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in_btn.setGeometry(QtCore.QRect(890, 170, 81, 41))
        self.zoom_in_btn.setObjectName("zoom_in_btn")
        self.zoom_out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out_btn.setGeometry(QtCore.QRect(1010, 170, 91, 41))
        self.zoom_out_btn.setObjectName("zoom_out_btn")
        dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Dashboard"))
        self.upload_btn.setText(_translate("dashboard", "Upload"))
        self.rotate_left_btn.setText(_translate("dashboard", "Rotate Left"))
        self.rotate_right_btn.setText(_translate("dashboard", "Rotate Right"))
        self.zoom_in_btn.setText(_translate("dashboard", "Zoom In"))
        self.zoom_out_btn.setText(_translate("dashboard", "Zoom Out"))
